### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by toniperic** [Blackmorse/hat-all-stats#196]
It would be great if there was documented how to run the project locally.

I'd like to toy around and contribute more eventually, but I'd rather not install any of the dependencies on my host machine, so I'm hoping there would be a containerized development setup, possibly using Docker?

**Comment by Blackmorse** [comment]
@toniperic . To build application you need java (for the loader), scala (for the web). Also you need a ClickHouse database.
For java you will need build tools gradle and maven, and sbt for scala.
Clickhouse can be installed at docker. 
But I'm not sure that docker is good choice for other stuff.
Is It ok for you?

If yes, I will prepare and write instructions .

**Comment by toniperic** [comment]
Yes, that would work.

Don't forget to specify exact versions of all the tooling/languages. :)

**Comment by Blackmorse** [comment]
@toniperic 
Ok, I'm working on it.
Also, what you will need for working - It is OAuth credentials: consumer key, secret and tokens.
I have them, but by term of usage and by security reasons I can't share It with you. 
So, I think we should work on  It together. 
I've added you to the contributers of CHHP app at Hattrick. Can you please  check your Hattrick's CHPP page?

**Comment by toniperic** [comment]
Yeah, it's there. 👍

**Comment by Blackmorse** [comment]
@toniperic  So you can start process of getting credentials. For me it takes some time..

**Comment by Blackmorse** [comment]
@toniperic I've pushed some instructions for running the app. Please check it. I will modify it according with you remarks

**Comment by Blackmorse** [comment]
Now docker-compose is available
