### ISSUE TITLE
Team name changes

### ISSUE THREAD

**Issue by toniperic** [Blackmorse/hat-all-stats#197]
As per [this submission](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17359875%26n%3D58%26v%3D2), looks like teams changing names results in duplicate results, which can be seen [here](https://hattid.com/leagueLevelUnit?leagueUnitId=258536).

**Comment by Blackmorse** [comment]
@toniperic thanks for reporting.
I will duplicate answer here:


The problem is that I can't distinguish between these two events(changind team name and changing team's owner).

I thought that separate teams with different owners is right solution. Maybe I was wrong :)

**Comment by Blackmorse** [comment]
Fixed.
