### ISSUE TITLE
[Feature] add possibility (was available in alltid) to compare teams that started around the same period (week)

### ISSUE THREAD

**Issue by akasolace** [Blackmorse/hat-all-stats#204]

**Comment by Blackmorse** [comment]
@akasolace , thanks for idea.
Unfortunately, I don't remeber how this type of comparison looked like at alltid.
If you can provide some additional info about that It would be great.

**Comment by Blackmorse** [comment]
@akasolace ,btw, this functionality had been added... Does you expected the same?

**Comment by akasolace** [comment]
Could ... I will have a look asap!

**Comment by akasolace** [comment]
This is a very nice addition, but what I would suggest is by default to display:
   - all rating information on same page table format (maybe ranked by default by power rating)
   - highlight own team in the table to have a quick grasp
 
so if not difficult to do I would do different filtering, something like,  within 'x' week(s):
   -  ,ight default to 1 but could offer for example 4, 8 and 16 weeks

**Comment by Blackmorse** [comment]
Your first suggestion is not fit perfectly with current Hattid data model. May I add several "tabs" corresponding to different ratings?

The second one is much more easier to implement.

**Comment by akasolace** [comment]
Ok then, you can stick with only display of Power rating, but if possible I would suggest the following improvement:
   - remove Season and Round columns (does not bring much  and it will improve visibility)
   - rank by default by Power Rating
   - include own team in the table and highlight it
   - replace filtering Season/Round per something like "within 'x' week(s):"  which might default to 1 but could offer for example 4, 8 and 16 weeks

**Comment by Blackmorse** [comment]
@akasolace,
I've made some work, and now Hattid data model fit your first suggestion.
But I have 13th different ranking indexes, and they will not fit in one table .. 
Do you have any ideas how it would be better to arrange this data?
Thanks

**Comment by Blackmorse** [comment]
@akasolace , Another iteration is done :) 
Now there are several tabs for rankings and the current team is highlighted

![image](https://user-images.githubusercontent.com/13163993/152301208-0898b1c0-5375-4b81-9204-2d5f2fa550c8.png)

**Comment by akasolace** [comment]
Looks great, Alltid keeps improving!
Do you think you can display the index ?  e.g. would display 9/28 if midfiled is selected but maybe 6/28 id attack is selected ....
